apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular9client
  namespace: nl-niveus-testing
  labels:
    app: angular9client
    version: "1.0"
    environment: testing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular9client
      version: "1.0"
      environment: testing
  template:
    metadata:
      labels:
        app: angular9client
        version: "1.0"
        environment: testing
    spec:
      containers:
      - name: angular9client-container
        image: atmohsin/angular9client:v1.0
        ports:
        - containerPort: 80