apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-rest-api
  namespace: nl-niveus-testing
  labels:
    app: spring-boot-rest-api
    version: "1.0"
    environment: testing
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-boot-rest-api
      version: "1.0"
      environment: testing
  template:
    metadata:
      labels:
        app: spring-boot-rest-api
        version: "1.0"
        environment: testing
    spec:
      containers:
      - name: spring-boot-rest-api-container
        image: atmohsin/spring-boot-rest-api:v6.0
        ports:
        - containerPort: 9090